name: PDFSorter
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates
  - certifi=2022.6.15
  - dateparser=1.1.1
  - libffi=3.4.2
  - openssl=1.1.1p
  - pip=21.2.4
  - python=3.10.4
  - python-dateutil=2.8.2
  - pytz=2022.1
  - regex=2021.8.3
  - setuptools=61.2.0
  - six=1.16.0
  - sqlite=3.38.5
  - tk=8.6.12
  - tzdata=2022a
  - tzlocal=2.1
  - vc=14.2
  - vs2015_runtime
  - wheel=0.37.1
  - wincertstore=0.2
  - xz=5.2.5
  - zlib=1.2.12
  - pip:
    - pypdf2==2.4.2
