name: PDFSorter
channels:
  - defaults
dependencies:
  - dateparser=1.1.1
  - pip=21.2.4
  - python=3.10.4
  - pip:
    - pymupdf=1.24.13
    - easyocr=1.7.2
    - torch==2.5.1
    - torchvision==0.20.1
