name: PDFSorter
channels:
  - defaults
  - nvidia
  - pytorch
dependencies:
  - dateparser=1.1.8
  - pip=24.2
  - python=3.10.15
  - pytorch=2.5.1
  - torchvision=0.20.1
  - pytorch-cuda=12.4
  - pip:
    - pymupdf==1.24.13
    - easyocr==1.7.2
